In [23]:
import streamlit as st
import pandas as pd
import plotly_express as px
import numpy as np
 

df = pd.read_csv('../vehicles_us.csv') 
df['manufacturer'] = df['model'].apply(lambda x: x.split()[0])

In [24]:
print(df.info())
(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: float64(4), int64(2), object(8)
memory usage: 5.5+ MB
None

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,manufacturer
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19,bmw
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50,ford
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79,hyundai
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9,ford
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28,chrysler

In [25]:
# Fill missing values in model_year with the median and convert to int
df['model_year'] = pd.to_numeric(df['model_year'], errors='coerce')
median_year = df['model_year'].median()
df['model_year'] = df['model_year'].fillna(median_year).astype(int)

# Convert cylinders to int with no decimal places
df['cylinders'] = pd.to_numeric(df['cylinders'], errors='coerce').fillna(0).astype(int)

#Fill in missing values in odometer with the median anc converting to int
df['odometer'] = pd.to_numeric(df['odometer'], errors='coerce')
median_odometer = df['odometer'].median()
df['odometer'] = df['odometer'].fillna(median_odometer).astype(int)

# Convert date_posted to datetime
df['date_posted'] = pd.to_datetime(df['date_posted'], errors='coerce')

In [26]:
print(df.info())
print(df['paint_color'].unique())
print(df['is_4wd'].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    51525 non-null  int64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  int64
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  int64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  datetime64[ns]
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(5), object(7)
memory usage: 5.5+ MB
None
[nan 'white' 'red' 'black' 'blue' 'grey' 'silver' 'custom' 'orange'
 'yellow' 'brown' 'green' 'purple']
[ 1. nan]

In [27]:
print(df.info())
# Display the first 25 rows of the DataFrame
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    51525 non-null  int64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  int64
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  int64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  datetime64[ns]
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(5), object(7)
memory usage: 5.5+ MB
None

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,manufacturer
0,9400,2011,bmw x5,good,6,gas,145000,automatic,SUV,NaN,1.0,2018-06-23,19,bmw
1,25500,2011,ford f-150,good,6,gas,88705,automatic,pickup,white,1.0,2018-10-19,50,ford
2,5500,2013,hyundai sonata,like new,4,gas,110000,automatic,sedan,red,NaN,2019-02-07,79,hyundai
3,1500,2003,ford f-150,fair,8,gas,113000,automatic,pickup,NaN,NaN,2019-03-22,9,ford
4,14900,2017,chrysler 200,excellent,4,gas,80903,automatic,sedan,black,NaN,2019-04-02,28,chrysler

In [28]:
df.describe()

,price,model_year,cylinders,odometer,is_4wd,date_posted,days_listed
count,51525.000000,51525.000000,51525.000000,51525.000000,25572.0,51525,51525.00000
mean,12132.464920,2009.838234,5.499932,115162.352179,1.0,2018-10-25 01:57:46.270742528,39.55476
min,1.000000,1908.000000,0.000000,0.000000,1.0,2018-05-01 00:00:00,0.00000
25%,5000.000000,2007.000000,4.000000,79181.000000,1.0,2018-07-29 00:00:00,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,2018-10-25 00:00:00,33.00000
75%,16839.000000,2014.000000,8.000000,146541.000000,1.0,2019-01-21 00:00:00,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,2019-04-19 00:00:00,271.00000
std,10040.803015,6.065836,2.431985,59909.264385,0.0,NaN,28.20427

In [29]:
# create a text header above the dataframe
st.header('Data viewer')
# display the dataframe with streamlit
st.dataframe(df)

2025-08-01 19:21:46.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:46.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:46.952 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:46.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [30]:
st.header('Vehicle types by manufacturer')
# create a plotly histogram figure
fig = px.histogram(df, x='manufacturer', color='type')
# display the figure with streamlit
st.write(fig)

2025-08-01 19:21:46.985 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:46.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:47.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:47.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:47.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-08-01 19:21:47.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
st.header('Histogram of `condition` vs `model_year`')
fig = px.histogram(df, x='model_year', color='condition')
st.write(fig)