In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
import streamlit as st

df = pd.read_csv('../vehicles_us.csv') 
df['manufacturer'] = df['model'].apply(lambda x: x.split()[0])

In [2]:
print(df.info())
(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   42258 non-null  object
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: float64(4), int64(2), object(8)
memory usage: 5.5+ MB
None

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,manufacturer
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19,bmw
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50,ford
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79,hyundai
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9,ford
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28,chrysler

In [ ]:
########## MODEL_YEAR ########## 
# Replace NaN in model_year with the median model_year for each model
df['model_year'] = df['model_year'].fillna(
    df.groupby('model')['model_year'].transform('median')
)
# Fill any remaining NaN in model_year with overall median before converting to int
df['model_year'] = df['model_year'].fillna(df['model_year'].median())
df['model_year'] = pd.to_numeric(df['model_year'], errors='coerce').astype(int)


########## CYLINDERS ########## 
# Replace NaN/null values in cylinders with the median cylinders for each model
df['cylinders'] = df['cylinders'].fillna(
    df.groupby('model')['cylinders'].transform('median')
)
#Convert cylinders to int with no decimal places
df['cylinders'] = pd.to_numeric(df['cylinders'], errors='coerce').fillna(0).astype(int)


########## ODOMETER ########## 
# Replavce NaN/null values in odometer value 0
df['odometer'] = df['odometer'].fillna(0)
# Replace 0 values in odometer with the median based on model_year and model
odometer_median = df.groupby(['model_year'])['odometer'].transform('median')
df['odometer'] = df['odometer'].mask((df['odometer'].isna()) | (df['odometer'] == 0), odometer_median)
# Convert odometer to int with no decimal places
df['odometer'] = pd.to_numeric(df['odometer'], errors='coerce').fillna(0).astype(int)


########### PAINT_COLOR ###########
# Change NaN values in paint_color to 'unknown'
df['paint_color'] = df['paint_color'].fillna('unknown')


########### IS_4WD ##########
# Change NaN values in is_4wd to 0
df['is_4wd'] = df['is_4wd'].fillna(0).astype(int)
# Convert is_4wd to int
df['is_4wd'] = df['is_4wd'].astype(int)


########## DATE_POSTED ########## 
# Convert date_posted to datetime
df['date_posted'] = pd.to_datetime(df['date_posted'], errors='coerce')


########## DAYS_LISTED ##########
# Replace 0 values in days_listed with the median value
df.loc[df['days_listed'] == 0, 'days_listed'] = df['days_listed'].median()

In [4]:
# Check for any NaN/null values in the whole DataFrame
print('NaN/null values in the whole DataFrame')
print(df.isna().sum())

NaN/null values in the whole DataFrame
price           0
model_year      0
model           0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
type            0
paint_color     0
is_4wd          0
date_posted     0
days_listed     0
manufacturer    0
dtype: int64

In [5]:
print('Values of 0 in columns')
# Check for any 0 values in all columns
print((df == 0).sum())

Values of 0 in columns
price               0
model_year          0
model               0
condition           0
cylinders           0
fuel                0
odometer            1
transmission        0
type                0
paint_color         0
is_4wd          25953
date_posted         0
days_listed         0
manufacturer        0
dtype: int64

In [6]:
print(df.info())
print(df['paint_color'].unique())
print(df['is_4wd'].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    51525 non-null  int32
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  int32
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  int32
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   51525 non-null  object
 10  is_4wd        51525 non-null  int32
 11  date_posted   51525 non-null  datetime64[ns]
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: datetime64[ns](1), int32(4), int64(2), object(7)
memory usage: 4.7+ MB
None
['unknown' 'white' 'red' 'black' 'blue' 'grey' 'silver' 'custom' 'orange'
 'yellow' 'brown' 'green' 'purple']
[1 0]

In [ ]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    51525 non-null  int32
 2   model         51525 non-null  object
 3   condition     51525 non-null  object
 4   cylinders     51525 non-null  int32
 5   fuel          51525 non-null  object
 6   odometer      51525 non-null  int32
 7   transmission  51525 non-null  object
 8   type          51525 non-null  object
 9   paint_color   51525 non-null  object
 10  is_4wd        51525 non-null  int32
 11  date_posted   51525 non-null  datetime64[ns]
 12  days_listed   51525 non-null  int64
 13  manufacturer  51525 non-null  object
dtypes: datetime64[ns](1), int32(4), int64(2), object(7)
memory usage: 4.7+ MB
None

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed,manufacturer
0,9400,2011,bmw x5,good,6,gas,145000,automatic,SUV,unknown,1,2018-06-23,19,bmw
1,25500,2011,ford f-150,good,6,gas,88705,automatic,pickup,white,1,2018-10-19,50,ford
2,5500,2013,hyundai sonata,like new,4,gas,110000,automatic,sedan,red,0,2019-02-07,79,hyundai
3,1500,2003,ford f-150,fair,8,gas,150000,automatic,pickup,unknown,0,2019-03-22,9,ford
4,14900,2017,chrysler 200,excellent,4,gas,80903,automatic,sedan,black,0,2019-04-02,28,chrysler

In [8]:
df.describe()

,price,model_year,cylinders,odometer,is_4wd,date_posted,days_listed
count,51525.000000,51525.000000,51525.000000,51525.000000,51525.000000,51525,51525.000000
mean,12132.464920,2009.793557,6.121067,114160.954139,0.496303,2018-10-25 01:57:46.270742528,39.589345
min,1.000000,1908.000000,3.000000,0.000000,0.000000,2018-05-01 00:00:00,1.000000
25%,5000.000000,2007.000000,4.000000,71900.000000,0.000000,2018-07-29 00:00:00,19.000000
50%,9000.000000,2011.000000,6.000000,114673.000000,0.000000,2018-10-25 00:00:00,33.000000
75%,16839.000000,2014.000000,8.000000,150000.000000,1.000000,2019-01-21 00:00:00,53.000000
max,375000.000000,2019.000000,12.000000,990000.000000,1.000000,2019-04-19 00:00:00,271.000000
std,10040.803015,6.099381,1.657457,61654.581361,0.499991,NaN,28.175963